import { cache } from "react";
import { supabase } from "@/lib/supabase";

/* =============================================================================
   Article index — read from Supabase
   =============================================================================
   This used to be a hardcoded array in lib/content.ts, regenerated by hand
   whenever an article's title, dek or read time changed. That coupling was the
   single most reliable source of wrong content on the site: the body would be
   corrected in Supabase and the listings, nav cards and sitemap would keep
   serving the old headline. It happened to the pets page, and it was live again
   on `panama-property-tax-exemption-extended` — whose content.ts entry still
   carried the retracted claim the rewrite exists to withdraw.

   Now there is one source of truth. Editing a title is a content operation
   again, not a deploy operation.

   Pairs with `export const revalidate` on every route that calls this. Without
   it the query still runs at build time only and nothing has changed.
   ============================================================================= */

export type ArticleIndexEntry = {
  slug: string;
  categorySlug: string;
  title: string;
  dek: string;
  /** Display string, e.g. "August 2026" — the shape the templates render. */
  updatedOn: string;
  readMinutes: number | null;
  /** Relative path; resolve through mediaUrl() before rendering. */
  ogImagePath: string | null;
};

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

/** `updated_on` is a date column and three rows still have it null, so fall
 *  back to when the row was published rather than rendering an empty slot. */
function displayDate(updatedOn: string | null, publishedAt: string | null): string {
  const raw = updatedOn ?? publishedAt;
  if (!raw) return "";
  const d = new Date(raw);
  if (Number.isNaN(d.getTime())) return "";
  return `${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
}

type Row = {
  slug: string;
  title: string;
  dek: string | null;
  read_minutes: number | null;
  updated_on: string | null;
  published_at: string | null;
  og_image_path: string | null;
  category: { slug: string } | { slug: string }[] | null;
};

/** Every published article. `cache` dedupes this across one render pass, so a
 *  page that needs both the listing and the related strip issues one query. */
export const listArticles = cache(async (): Promise<ArticleIndexEntry[]> => {
  const { data, error } = await supabase
    .from("articles")
    .select(
      `slug, title, dek, read_minutes, updated_on, published_at, og_image_path,
       category:categories ( slug )`,
    )
    .eq("status", "published")
    .order("slug");

  if (error || !data) return [];

  return (data as Row[])
    .map((r) => {
      const cat = Array.isArray(r.category) ? r.category[0] : r.category;
      if (!cat) return null;
      return {
        slug: r.slug,
        categorySlug: cat.slug,
        title: r.title,
        dek: r.dek ?? "",
        updatedOn: displayDate(r.updated_on, r.published_at),
        readMinutes: r.read_minutes,
        ogImagePath: r.og_image_path,
      };
    })
    .filter((a): a is ArticleIndexEntry => a !== null);
});

export const listArticlesIn = async (categorySlug: string) =>
  (await listArticles()).filter((a) => a.categorySlug === categorySlug);

/** Same category first, then anything else, so "Keep reading" points at
 *  something adjacent instead of the first three slugs alphabetically. */
export async function relatedArticles(
  categorySlug: string,
  slug: string,
  limit = 3,
): Promise<ArticleIndexEntry[]> {
  const all = (await listArticles()).filter(
    (a) => !(a.slug === slug && a.categorySlug === categorySlug),
  );
  const sameCategory = all.filter((a) => a.categorySlug === categorySlug);
  const rest = all.filter((a) => a.categorySlug !== categorySlug);
  return [...sameCategory, ...rest].slice(0, limit);
}
